### ISSUE TITLE
Sourcemap is missing

### ISSUE THREAD

**Issue by mark-veenstra** [atatus/atatus-js#1]
When we run the application on Android or IOS using Apache Cordova we sometimes hit the error that the sourceMap (`atatus.min.js.map`) isn't found in the `www/lib/atatus-js/ folder`.

We installed Atatus using:  `bower install`

Also on the GitHub page I don't see any `atatus.min.js.map` file in the project. Removing the sourceMap from the `atatus.min.js` file resolved the issue: https://github.com/atatus/atatus-js/blob/master/atatus.min.js#L5

Can you please check and fix?

**Comment by fizerkhan** [comment]
@mark-veenstra Sorry for the issue. Now we removed sourcemap link from our minified file. From version 2.3.6, you don't face this issue.
