### ISSUE TITLE
Feature Request: Allow failures in atatus.recordTransaction()

### ISSUE THREAD

**Issue by azaslavsky** [atatus/atatus-js#5]
I've been using transactions so far and loving them, especially as a means to measure the loading performance of various iframed resources in my app.  As I understand it, `atatus.recordTransaction('foobar', 1000);` is more or less shorthand for

```javascript
atatus.startTransaction('foobar');
setTimeout(() => {
  atatus.endTransaction('foobar');
}, 1000);
```

Would it be possible to extend the `atatus.recordTransaction()` method to do the same for failed transactions?  Ie, something like `atatus.recordFailedTransaction('foobar', 1000);` or `atatus.recordTransaction('foobar', 1000, false);`?

**Comment by fizerkhan** [comment]
@azaslavsky Added support for recordTransaction. https://docs.atatus.com/docs/browser-monitoring/browser-agent-api/custom-transactions.html#recording-a-transaction-with-duration
