### ISSUE TITLE
Config, Notify not exported when importing with Rollup

### ISSUE THREAD

**Issue by KayakinCoder** [atatus/atatus-js#6]
Hi folks, trying to set things up and we use Rollup

```
import * as atatus from 'atatus-js';
atatus.config('our api key').install();
```

gives us the following notices in Rollup

> 'config' is not exported by 'node_modules\atatus-js\atatus.min.js'
> 'notify' is not exported by 'node_modules\atatus-js\atatus.min.js'

and the following console error which occurs at atatus.config

> Uncaught TypeError: undefined is not a function

Rollup typically does best if it has access to an ES module. I'm not an expert on packages, but usually exporting an ES module and updating your package.json so that it defines that module's availability does the trick

**Comment by fizerkhan** [comment]
@KayakinKoder We have exported atatus as `module.exports = atatus;`. In rollup, [rollup-plugin-commonjs](https://github.com/rollup/rollup-plugin-commonjs) converts this export into `export default atatus`. So you have to import as follows 

    import atatus from 'atatus-js';
    atatus.config('our api key').install();

Please try and let me know.

**Comment by KayakinCoder** [comment]
Works great, thanks
